artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    n_rows: 10000
    raw_data_path: app/data/heart-disease.csv
    loaded_data_path: artifacts/data_ingestion/loaded_heart-disease.csv
    chunk_size: 100000