artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    n_rows: 10000
    raw_data_path: app/data/heart-disease.csv
    loaded_data_path: artifacts/data_ingestion/loaded_heart-disease.csv
    chunk_size: 100000

data_cleaning:
    root_dir: artifacts/data_cleaning
    loaded_data_path: artifacts/data_ingestion/loaded_heart-disease.csv
    clean_data_path: artifacts/data_cleaning/clean_heart-disease.csv
    chunk_size: 100000

data_transformation:
    root_dir: artifacts/data_transformation
    clean_data_path: artifacts/data_cleaning/clean_heart-disease.csv
    transformed_data_path: artifacts/data_transformation/transformed_heart-disease.csv
    chunk_size: 100000
    train_data_path: artifacts/data_transformation/train.csv
    test_data_path: artifacts/data_transformation/test.csv