

name: Build and deploy Python app to Azure Web App - hdpredictor
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Docker image to Azure Web App
      run: |
          az webapp config container set \
            --name hdpredictor \
            --resource-group hdpredictor2 \
            --container-image-name soyinkas1/hdpredictor:latest \
            --container-registry-url https://index.docker.io/v1/ \
            --container-registry-user ${{ secrets.DOCKERHUB_USERNAME }} \
            --container-registry-password ${{ secrets.DOCKERHUB_TOKEN }}
