# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - hdpredictor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set environment variables
        run: |
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings DATABASE_URL=${{ secrets.DATABASE_URL }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings DEV_DATBASE_URL=${{ secrets.DEV_DATABASE_URL }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings FLASK_CONFIG=${{ secrets.FLASK_CONFIG }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings MAIL_PORT=${{ secrets.MAIL_PORT }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings MAIL_SERVER=${{ secrets.MAIL_SERVER }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings MAIL_SUBJECT_PREFIX=${{ secrets.MAIL_SUBJECT_PREFIX }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings MAIL_USE_TLS=${{ secrets.MAIL_USE_TLS }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings SECRET_KEY=${{ secrets.SECRET_KEY }}
          az webapp config appsettings set --resource-group hdpredictor --name hdpredictor --settings SQLALCHEMY_TRACK_MODIFICATIONS=${{ secrets.SQLALCHEMY_TRACK_MODIFICATIONS }}
          
        
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'hdpredictor'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2305B597B54D453C8C4CB8C5863BF367 }}
